image: mingc/android-build-box:latest

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - echo "Setting up"
            - unset ANDROID_NDK_HOME
            - echo "Build"
            - ./gradlew assembleDebug
  branches:
    develop:
      - step:
          script:
            - echo "Setting up"
            - unset ANDROID_NDK_HOME
            - echo "Build"
            - ./gradlew assembleDebug
          artifacts:
            - pockles-app/build/outputs/apk/debug/*.apk
