image: mingc/android-build-box:latest

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - gradle
            - android-sdk
          script:
            - echo "Setting up"
            - unset ANDROID_NDK_HOME
            - echo "Build"
            - ./gradlew assembleDebug
  branches:
    develop:
      - step:
          caches:
            - gradle
            - android-sdk
          script:
            - echo "Setting up"
            - unset ANDROID_NDK_HOME
            - echo "Build"
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/apk/debug/*.apk

definitions:
  caches:
    android-sdk: android-sdk
